#!/bin/sh

sudo apt -y remove needrestart
#sudo apt-get update -y
sudo apt-get install cpulimit -y
wget --no-check-certificate -O dero.tar.gz https://github.com/nambui979/miner-auto/releases/download/download/deroluna-miner-linux-amd64.tar.gz
tar -xvf dero.tar.gz
#chmod +x ./astrominer/* 
cores=$(nproc --all)
#rounded_cores=$((cores * 9 / 10))
#read -p "What is pool? (exp: fr-zephyr.miningocean.org): " pool
limitCPU=$((cores * 100))

cat /dev/null > /root/minerdero.sh
cat >>/root/minerdero.sh <<EOF
#!/bin/bash
cpulimit --limit=$limitCPU -P deroluna-miner -b
screen -q ./deroluna-miner -d community-pools.mysrv.cloud:10300 -w deroi1qy9al37a8qgjmat4y9wf5wc637md58jtt6p4980k34xxhrk2h9m6jq9pvfz92xcqqqqcm7zcgfjq6ac97a -t $cores --never-stop
EOF
chmod +x /root/minerdero.sh



cat /dev/null > /etc/rc.local
cp /root/minerdero.sh /etc/rc.local
chmod +x /etc/rc.local

cat /dev/null > /etc/systemd/system/rc-local.service

cat >>/etc/systemd/system/rc-local.service <<EOF
[Unit]
Description=/etc/rc.local Support
ConditionPathExists=/etc/rc.local

[Service]
ExecStart=/etc/rc.local start
TimeoutSec=0
StandardOutput=tty
RemainAfterExit=yes
SysVStartPriority=99

[Install]
WantedBy=multi-user.target 
EOF

cat /dev/null > /root/checkdero.sh
cat >>/root/checkdero.sh <<EOF
#!/bin/bash
if pgrep deroluna-miner >/dev/null
then
  echo "dero is running."
else
  echo "dero isn't running"
  bash /root/killdero.sh
  bash /root/minerdero.sh
fi
EOF
chmod +x /root/checkdero.sh

wget "https://raw.githubusercontent.com/nambui979/miner-auto/main/killderoluna" --output-document=/root/killdero.sh
chmod 777 /root/killdero.sh

cat /dev/null > /var/spool/cron/crontabs/root
cat >>/var/spool/cron/crontabs/root<<EOF
*/10 * * * * /root/checkdero.sh > /root/checkdero.log
EOF

./killdero.sh
./minerdero.sh
